// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxpdcmnzbgjwryqewaiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cGRjbW56Ymdqd3J5cWV3YWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTAxOTksImV4cCI6MjA2NDE4NjE5OX0.5BVmx2tCfeNfCbHfGUdkOs5Q0dYpqjSXnVresWS9BWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);